### ISSUE TITLE
Cucumber.js => Report Portal

### ISSUE THREAD

**Issue by bolatbekb** [reportportal/client-javascript#1]
Здравствуйте, уважаемый разработчик клиента на JS.

Подскажите, как правильно отправлять данные о прохождении теста в Report Portal при использовании Cucumber.js

Хотелось бы видеть в Report Portal результат прохождения теста следующим образом:
1 уровень - релиз (тут префикс и номер релиза, например, "hotfix 1.1.1a";
2 уровень - группа тестов (например, backoffice, front, widgets и так далее);
3 уровень - название фичи файла (берем из Feature:);
4 уровень - название сценария (берем из Scenario:);
5 уровень - название шагов (берем из Given/When/Then).

Возможно, есть у вас другие предложение как это должно выглядеть, тоже рассмотрел бы: 
- к примеру, убрать 2 уровень, название групп вынести в теги и фильтровать как надо, в любом случае, мы же смотрим только на падения тестов, лично мне степы не очень интересно смотреть и хранить в RP )). Главное, чтобы и анализатор ошибок работал.
- к примеру, может нам не понадобится 5й уровень, достаточно выложить трейс ошибки + названием шага.

Я планирую не отправлять в report portal  в онлайне, а парсить результатв прогона тестов (файлы *.xml).

**Comment by szikszail** [comment]
@bolatbekb as we discussed on Slack #2 block you, @tkachoff  cloud you please check on it?

**Comment by DzmitryHumianiuk** [comment]
@bolatbekb @szikszail #2 closed and merged
