### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by xadvfh** [reportportal/client-javascript#102]
I'm getting the following certificate error running the jest agent:

```
Error: unable to verify the first certificate
    at C:\Users\username\source\repos\project-name\src\project\ClientApp\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
```

I'm using Report Portal 5 with jest agent 5.0.1

**Comment by xadvfh** [comment]
If I disable SSL, via `export NODE_TLS_REJECT_UNAUTHORIZED=0`

```
Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'name' should not be null.] "}
    at C:\Users\username\source\repos\project-name\src\project\ClientApp\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at runMicrotasks (<anonymous>)
```

Maybe that helps provide some more context into the error.

**Comment by xadvfh** [comment]
I have verified that this error is thrown by axios when you use a self-signed certificate.  We need a way to either set `https.Agent({rejectUnauthorized: false})` or a way for agents to pass certs that should be trusted.

**Comment by xadvfh** [comment]
@AmsterGet Can someone look at this please?  It is blocking my team completely.

**Comment by AmsterGet** [comment]
Hi @xadvfh !
Unfortunately, our team is completely busy with other things.
Next week, I will try to take the time to investigate this issue and determine our next steps.

**Comment by xadvfh** [comment]
@AmsterGet just checking in on this again.

**Comment by xadvfh** [comment]
@AmsterGet another ping.  This bug is making it so report portal cannot be used with self-signed certificates.

**Comment by alena-rak** [comment]
Hello. I'm facing this issue too, is there any update @AmsterGet? @xadvfh maybe you found some workaround?

**Comment by xadvfh** [comment]
@alena-rak the only work around i've found is to fork this package and set `https.Agent({rejectUnauthorized: false})` and use the forked package.
 
it's unfortunate that such an important blocking issue is not getting any traction @AmsterGet

**Comment by AmsterGet** [comment]
@xadvfh @alena-rak Hi guys!
Sorry for delay.
Unfortunately, our team currently lacks resources to address this issue.
If it will be possible to inject the `https agent` parameters into axios from the client config, would that work for you?

**Comment by alena-rak** [comment]
@AmsterGet yes, seems like that would solve the issue

**Comment by xadvfh** [comment]
@AmsterGet yes that should work

**Comment by xadvfh** [comment]
@AmsterGet another ping.

**Comment by AmsterGet** [comment]
@xadvfh 
Added to milestone `5.0.4`. We don't have an exact release date at this time.
Also this improvement needs to be added to all of our agent-js-*, so it may take longer.
