### ISSUE TITLE
Security depdency issue (axios)

### ISSUE THREAD

**Issue by jay-espiritu** [reportportal/client-javascript#109]
Implemented security scanning in my pipeline and started failing cause of `axios` dependency. Is it possible for it to be updated to `>=0.21.1`version? Would there be any repercussion doing so?

![Screen Shot 2021-04-19 at 12 42 56 pm](https://user-images.githubusercontent.com/21213499/115174555-cd3df000-a10c-11eb-89b2-37c1632fcc10.png)

**Comment by AmsterGet** [comment]
Hello @jay-espiritu !
The fix is already in develop branch and waiting for release.
Coming soon, stay tuned!
