### ISSUE TITLE
Fail to start test Error: timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by anushaengu** [reportportal/client-javascript#115]
I could see you have changed axios timeout to 5000ms, we are using Cypress report portal plugin which in turn uses this.

Can you please provide us a provision to change this timeout from outside as our bamboo servers are pretty slow and all are failing with 

//Fail to start test Error: timeout of 5000ms exceeded
	Error: timeout of 5000ms exceeded
error	   at /e2e/node_modules/@reportportal/cypress/node_modules/@reportportal/client-javascript/lib/rest.js:34:23

**Comment by AmsterGet** [comment]
Hi @anushaengu !
This feature is under development and will be released during this business week (May 24-28).
Stay tuned!

**Comment by Bunyamin-Shabanov-Cloudeou** [comment]
> Hi @anushaengu !
> This feature is under development and will be released during this business week (May 24-28).
> Stay tuned!

Hello there! I'm sorry but that did not help in our situation(I'm not related to the author of this issue in any way). Now your lib says: Error: timeout of 1ms exceeded. Unfortunately, I could get this output after a great tweak of my openshift pod. You do not log anything except 503 error so I had to manage it myself. The most interesting part is that this error does not occur when running tests on local Windows/MacOs machine.
