### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by coltdorsey** [reportportal/client-javascript#129]
I've had report portal configured and working for quite some time, but suddenly I'm getting the following error: 

```
Fail to finish launch Error: Request failed with status code 401: {"error":"unauthorized","error_description":"Full authentication is required to access this resource"}
    at /Users/<redacted>/project/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

 I've tried refreshing access tokens, but the error persists. Any pointers would be helpful. Thanks!

**Comment by AmsterGet** [comment]
Hello @coltdorsey !
Does the rest of the requests work as expected?
Are the project and endpoint parameters correct as well?

**Comment by coltdorsey** [comment]
For our case, 

Dependabot upgraded follow-redirects from 1.14.4 to 1.14.8 on 2/14 to address security vulnerabilities, but follow-redirects 1.14.8 has a bug that breaks authentication to Report Portal. We upgraded follow-redirects 1.14.9 released on 2/18 (last Friday) which fixes the authentication error.

**Comment by AmsterGet** [comment]
@coltdorsey Thanks for this explanation. We'll bump this package in the next release version.
