### ISSUE TITLE
Step is handled like test.

### ISSUE THREAD

**Issue by dubilyer** [reportportal/client-javascript#148]
When creating a 'STEP' test item under the 'TEST'

` client.startTestItem(
      { name, description, type: 'STEP' },
      launchTempId,
      testTempId,
    );
  `

I see the total amount of steps in the launch view (Total column), and Method Type = test in a test view.
So if I have 5 tests with 10 steps in each one, I see Total: 50 instead of 5.
Do I miss something?

**Comment by dubilyer** [comment]
Ok, I realized. I should use hasStats: false

**Comment by AmsterGet** [comment]
Hello @dubilyer !
The ReportPortal consider items with `type: STEP` as test cases (entity containing statistics), so if you want to see statistics the items with `type: STEP` and without `hasStats: false` need to be reported anyway.
Basically, the steps with `hasStats: false` used for reporting Nested steps, see [docs](https://reportportal.io/docs/dev-guides/ReportingDevelopersGuide/#start-childnested-step-item), [nested steps wiki](https://github.com/reportportal/client-java/wiki/Nested-steps).

**Comment by dubilyer** [comment]
@AmsterGet would be great if you can explain how to make nested steps collapsible!

**Comment by AmsterGet** [comment]
It will be able to collapse/expand if it has children - other nested steps or logs.

**Comment by dubilyer** [comment]
Got it. Thanks for your support.
