### ISSUE TITLE
[vitest] Any possibility of integration with vitest ? 

### ISSUE THREAD

**Issue by ViktarDrummer** [reportportal/client-javascript#152]
Hello. 

Just wandering is it possible to integrate RP with vitest ? 
I tried to find any info about that, but with no results, maybe you may help me with some hints? 

Thank you in advance.

**Comment by AmsterGet** [comment]
Hello @ViktarDrummer !
Yes, it is possible using this repo as SDK and following our [guides](https://reportportal.io/docs/dev-guides/ReportingDevelopersGuide). The easiest way as I see is to implement a Vitest [reporter](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/types/reporter.ts) interface and use it as mentioned [here](https://vitest.dev/config/#reporters).
We have no immediate plans (at least in 2023) to implement an agent to support this integration, but this may change in the future.
In the meantime, we are open to contributions, and you can implement them yourself. 😃

Feel free to ask any questions.

**Comment by ViktarDrummer** [comment]
Thank you for answer.

**Comment by AmsterGet** [comment]
Hi @ViktarDrummer !
I decided to re-open the ticket to collect community interest on this integration.
Just curious if you were able to create it yourself?

**Comment by AmsterGet** [comment]
Hi @ViktarDrummer !
Meet [agent-js-vitest](https://github.com/reportportal/agent-js-vitest)!
We've just released its first version. Feel free to left your feedback!
