### ISSUE TITLE
ReferenceError: atob is not defined for client-javascript/statistics/constants.js (NODEJS version <16)

### ISSUE THREAD

**Issue by irinaspivak** [reportportal/client-javascript#156]
client-javascript latest version 5.0.9
Issue with client-javascript/statistics/constants.js Line 13
const CLIENT_INFO = atob('Ry1XUDU3UlNHOFhMOmVFazhPMGJ0UXZ5MmI2VXVRT19TOFE=');

This line fails on NODEJS version lower then 16. 
Could you please adjust the code to match both <16 and >16 NODEJS.

**Comment by AmsterGet** [comment]
Hello @irinaspivak !
Thanks for pointing this out!
I'm working on a fix right now and will let you know when it's ready.
In the meantime, specify version 5.0.8 of this library as a workaround.

**Comment by AmsterGet** [comment]
@irinaspivak
The compatibility issues have been fixed. Please check version 5.0.10.
A few questions:
What version of Node.js are you using?
Do you plan to upgrade to the latest versions with LTS support?

**Comment by irinaspivak** [comment]
@AmsterGet, thanks a lot for quick response and action! We were using version 14 and temporarily moved to 16 to overcome this issue yesterday. We are planning to move to version 18 this year.
