### ISSUE TITLE
Launch not found error occuring

### ISSUE THREAD

**Issue by vininaag** [reportportal/client-javascript#17]
I have the launchObj.tempId of my previous run which i haven't closed. In the portal it shows as running. I don't want to see that. So 
I created a RPCClient and trying to call finishLaunch with that launchObj.tmpId (like below).
```
rpClient.finishLaunch('d19a23vxjfusj87z', {
    end_time: rpClient.helpers.now()
});
```

//Result
```
(node:98508) UnhandledPromiseRejectionWarning: Error: Launch "d19a23vxjfusj87z" not found
    at RPClient.finishLaunch (/Users/bojjawan/REPOS/ui-web-e2e-tests/node_modules/reportportal-client/lib/report-portal-client.js:142:55)
```

**Comment by BorisOsipov** [comment]
Hi @vininaag 

It's actually not a bug. Current client implementation doesn't support any action with launch that has been ran from other client instance.
