### ISSUE TITLE
Send log fails with authorization error

### ISSUE THREAD

**Issue by vadimromanyak** [reportportal/client-javascript#18]
An intermittent issue occurs with sendLog method: helper.getServerResult fails with authorizationError: `UNABLE_TO_VERIFY_LEAF_SIGNATURE`. Issue is reproduced if we send 7-8 logs in single step (presence of file in log doesn't matter). sendLog promise is pending, step hangs in progress status and so on with scenario, feature, launch. 

reportportal-client v5.1.0

**Comment by evjlobanova** [comment]
@vadimromanyak unfortunately we do not have any contributors on js now. You can try to fix the issue by yourself and send us PR.

**Comment by vadimromanyak** [comment]
@evjlobanova if sendLog method fails, then sendLog promise is rejected, catch block doesn't finish test item. finish test item is only supposed to happen if sendLog promise is resolved. thus, step/scenario/feature/launch will never get closed. is it expected behavior for run to hang in progress if RP client faces a single exception? 
will it be acceptable fix if catch block handles this error? so step/launch still get closed even upon getting an exception?

**Comment by BorisOsipov** [comment]
@vadimromanyak what agent(mocha\jasmine\etc) do you use?

**Comment by vadimromanyak** [comment]
finishTestItem handles promise returned by sendLog. finishTestItem resolves promises of his children (which are logs) using Promise.all. If at least single child promise is rejected, then Promise.all "rejects with the reason of the first promise that rejects". thus, finishTestItem skips callback to close test item, and falls to catch. last one doesn't perform any actions, so test item remains in progress status. this progress step prevents subsequent parents and launch from being closed as well.

**Comment by avarabyeu** [comment]
@vadimromanyak i would suggest adding some retries here. Unfortunately, if some test item isn't closed, server rejects closing its parent. So, it doesn't really make sense to try to close all chain of parent. There only exception here is sending logs actually. Rejected log is not considered as reason to reject closing test item.

**Comment by vadimromanyak** [comment]
@avarabyeu thanks, I've considered this same way. Can ES6 be used to make a fix? This will enable to replace Promise.all with an async for .. of and get all sendLog promises fulfilled.

**Comment by DzmitryHumianiuk** [comment]
@vadimromanyak is it fixed after code merge #19 ?

**Comment by vadimromanyak** [comment]
@DzmitryHumianiuk No. Merged code solves the problem when part of pending promises were completely lost. But "authorizationError: UNABLE_TO_VERIFY_LEAF_SIGNATURE" is still there.

**Comment by BorisOsipov** [comment]
@vadimromanyak do you think `"authorizationError: UNABLE_TO_VERIFY_LEAF_SIGNATURE"` issue can be sovled by some changes in `client-javascript` library? I am not sure, so I think this issue should be closed or moved to another repo.

**Comment by DzmitryHumianiuk** [comment]
`UNABLE_TO_VERIFY_LEAF_SIGNATURE` related to SSL certificate
