### ISSUE TITLE
Sub-item creation is not correct

### ISSUE THREAD

**Issue by szikszail** [reportportal/client-javascript#2]
Hi,

There is an issue in the code, here: https://github.com/reportportal/client-javascript/blob/master/lib/client.js#L51
The expression should be the opposite :)

**Comment by avarabyeu** [comment]
@szikszail feel free to make pull request :)

**Comment by szikszail** [comment]
Created ;)

**Comment by tkachoff** [comment]
Merged. Thanks, Laszlo!
