### ISSUE TITLE
Does anyone have an example of mergeLaunches method?

### ISSUE THREAD

**Issue by lucas-sebastian-deel** [reportportal/client-javascript#219]
Hi community, I would like to know if anyone achieve to use mergeLaunches method:

https://github.com/reportportal/client-javascript?tab=readme-ov-file#mergelaunches

```
rpClient.mergeLaunches({
    description: 'Regression tests',
    attributes: [
      {
        key: 'build',
        value: '1.0.0'
      }
    ],
    endTime: rpClient.helpers.now(),
    extendSuitesDescription: false,
    launches: [1, 2, 3],
    mergeType: 'BASIC',
    mode: 'DEFAULT',
    name: 'Launch name',
})
```

I tried to use it, but I'm not sure in which part of the code we should call this method + I'm not sure how we can get the 'real launch ids' to use in 'launches array'.

I'm using jest agent -> https://github.com/reportportal/agent-js-jest 

Thanks in advance 🙌

**Comment by lucas-sebastian-deel** [comment]
Please, any info about this 🙏

**Comment by lucas-sebastian-deel** [comment]
Please, any info about this 🙏

**Comment by AmsterGet** [comment]
Hi @lucas-delafuente-deel !
I've created a small guide regarding this feature for the [Playwright agent](https://github.com/reportportal/agent-js-playwright?tab=readme-ov-file#merging-launches-based-on-the-build-id).
You can refer it as the approach should be the same for all integrations.
Just curious, what is your use case? Do you shard your execution and willing to join it at the end?

**Comment by AmsterGet** [comment]
Hi @lucas-delafuente-deel !
Has this guide been helpful to you?
Thank you in advance.

**Comment by lucas-sebastian-deel** [comment]
Hi mate, sorry for the delay.
I haven't tried again because the focus of the tasks has changed a bit, I will try to test it in next weeks, I can leave a message here regarding the guide, but feel free to close the issue.

**Comment by AmsterGet** [comment]
Hi @lucas-delafuente-deel !
Sure, take your time )
