### ISSUE TITLE
restler dependency imports qs library, which has a security vulnerability

### ISSUE THREAD

**Issue by thephilwells** [reportportal/client-javascript#25]
Is there a safer way to manage query parameters than by using `restler`?

https://app.snyk.io/test/npm/wdio-reportportal-reporter/0.0.21?tab=dependencies

**Comment by DzmitryHumianiuk** [comment]
@BorisOsipov I guess it's for you ^

**Comment by BorisOsipov** [comment]
Nope. restler is client-javascript dependency

**Comment by BorisOsipov** [comment]
I will submit PR soon with replacing restler with axios.
