### ISSUE TITLE
Launch "xxx" not found. Did you use correct Launch ID?

### ISSUE THREAD

**Issue by kerly** [reportportal/client-javascript#35]
Following up on this issue: https://github.com/reportportal/client-javascript/issues/17   
The issue resolution mentions that the client does not support launches started from other client instance. But the README documentation states that we can pass the `id` of a launch to use an existing launch.

```
    //this param used only when you need client to send data into the existing launch
    id: 'id'
``` 

Is there any support for connecting to an existing launch from another client? If not; is that work planned to be worked? If not; does anyone know what needs to be done to support it? I cannot use this client without that functionality.

Thanks

**Comment by BorisOsipov** [comment]
@kerly 
you can pass `id` to `startLaunch` to use existing launch and it must be real launch id but not temporary that startLaunch returns

```
const {promise, tempId} = client1.startLaunch({description, mode, tags});
const {id: realLaunchId} = await promise;
///// some code

newClient.startLaunch({id: realLaunchId});
```

**Comment by kerly** [comment]
@BorisOsipov Yes, using the realId makes this work as expected. Thank you very much!
