### ISSUE TITLE
Url generated for items with parent item failes at url format validation throws 500 error

### ISSUE THREAD

**Issue by abhilashjoseph** [reportportal/client-javascript#37]
Url generated has an extra '/' which results in 500 error when posted, url normalize error from springboot
Error: Request failed with status code 500: {"timestamp":1570548010493,"status":500,"error":"Internal Server Error","message":"The request was rejected because the URL was not normalized.","path":"/v1/[projectname]/item//[guid]"}
    at axios.then.catch (/usr/local/lib/node_modules/@reportportal/newman-reporter-reportportal/node_modules/reportportal-client/lib/rest.js:27:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by abhilashjoseph** [comment]
I have fixed this, but i'm unable to push this to a branch for PR

**Comment by abhilashjoseph** [comment]
submitted PR, please review

**Comment by DzmitryHumianiuk** [comment]
Accepted and merged.
Thank you!

**Comment by abhilashjoseph** [comment]
Is there a schedule when the npm package version gets pushed to the registry with the latest changes?

**Comment by DzmitryHumianiuk** [comment]
@abhilashjoseph by manual trigger.
just triggered it.
It says that uploaded successfully.
plz check

**Comment by abhilashjoseph** [comment]
Thank you! I see the latest version now!
