### ISSUE TITLE
configParser error when running protractor suite

### ISSUE THREAD

**Issue by ParmaJonEman** [reportportal/client-javascript#41]
It runs fine locally, but when I run my protractor suite via jenkins, I'm getting:

`12:59:04 [12:59:04] E/configParser - Error code: 105
12:59:04 
12:59:04 [12:59:04] E/configParser - Error message: failed loading configuration file protractor.conf.js
12:59:04 [12:59:04] E/configParser - C:\automation\agent2\workspace\Development\Novo\Automation\CustomObject\Contact\node_modules\reportportal-client\lib\report-portal-client.js:135
12:59:04             );
12:59:04             ^
12:59:04 SyntaxError: Unexpected token )`

And when I navigate to that section of report-portal-client.js, I see:

`        if (launchDataRQ.id) {
            this.map[tempId] = this.getNewItemObj(resolve => resolve(launchDataRQ));
            this.map[tempId].realId = launchDataRQ.id;
        } else {
            const launchData = Object.assign(
                { name: this.config.launch || 'Test launch name', start_time: this.helpers.now() },
                launchDataRQ,
            );`

All I can see that would possible be causing this is the extra comma after launchDataRQ at the end, but I imagine other people would be seeing this issue too, if that was the case. I'm using Protractor 5.4.2 in both instances.

Any suggestions or anything obvious I'm not trying?

**Comment by BorisOsipov** [comment]
@ParmaJonEman check your nodejs version in jenkins is the same as local first. Tralling comma is supported in modern js and should not be a problem.

**Comment by evjlobanova** [comment]
@ParmaJonEman did you resolved this issue?

**Comment by ParmaJonEman** [comment]
I am currently in the process of getting nodejs version updated in jenkins. Due to needing to follow workplace procedures, it could be a couple weeks before I know if this solved the issue.

**Comment by ParmaJonEman** [comment]
This was resolved by updating nodejs. Thank you.
