### ISSUE TITLE
Ambiguous licensing

### ISSUE THREAD

**Issue by Ricool06** [reportportal/client-javascript#43]
Hi all,
I noticed that your package.json still says the license is GPL-3, but the license.txt states the source code is now Apache 2. Could we make the licensing consistent to prevent misunderstanding?

**Comment by evjlobanova** [comment]
@KatsiarynaTatarynovich please double check that for all js agents for ver 5.0 should be applyed Apache 2

**Comment by DzmitryHumianiuk** [comment]
should be Apache 2.0 in all of them

**Comment by Ricool06** [comment]
#46 remedies this issue when merged
