### ISSUE TITLE
NPM 2 versions of report-portal

### ISSUE THREAD

**Issue by vaiulian** [reportportal/client-javascript#47]
Hi

So i'm trying to use the `client-javascript` to send logs to Report-Portal and i found 2 modules on NPM Registry, both targeting this repo:

https://www.npmjs.com/package/reportportal-client-restler v1.0.0

https://www.npmjs.com/package/reportportal-client v5.2.3

Any ideas?

**Comment by evjlobanova** [comment]
@KatsiarynaTatarynovich Could you please check this issue?

**Comment by KatsiarynaTatarynovich** [comment]
@vaiulian 
Hi
You should use this package https://www.npmjs.com/package/reportportal-client v5.5.0
Could you please specify what kind of agent you use?

**Comment by vaiulian** [comment]
@KatsiarynaTatarynovich @evjlobanova 

Hey, 
so been trying to use this https://www.npmjs.com/package/agent-js-cypress

the version 1.1.3 uses "reportportal-client-restler": "^1.0.0" - develop branch
and version 1.1.2 uses "reportportal-client": "^5.2.1" - master branch

**Comment by KatsiarynaTatarynovich** [comment]
@vaiulian 
We refactoring **agent-js-cypress** to meet changes of version 5 at the moment, after releasing this agent we will have the only "reportportal-client" package. It should be updated soon.

**Comment by KatsiarynaTatarynovich** [comment]
@vaiulian we close this issue,  feel free to reopen it
