### ISSUE TITLE
Error with `rerun` option

### ISSUE THREAD

**Issue by kobenguyent** [reportportal/client-javascript#51]
I called `startLaunch` with `rerun` option and I got this error at the end

```sh
Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [query did not return a unique result: 2]"}
    at /Users/thanhnguyen/Desktop/codeceptjs-rest-demo/node_modules/reportportal-client/lib/rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [query did not return a unique result: 2]"}
    at /Users/thanhnguyen/Desktop/codeceptjs-rest-demo/node_modules/reportportal-client/lib/rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any help would be appreciated!

**Comment by DiscoElevator** [comment]
Hello, @PeterNgTr 
Which RP version do you use?
Do you start new launch with the same name as the launch you try to rerun?

**Comment by kobenguyent** [comment]
Hi @DiscoElevator , I'm using this RP https://web.demo.reportportal.io/
> Do you start new launch with the same name as the launch you try to rerun?

I think yes :)

**Comment by evjlobanova** [comment]
@PeterNgTr I suppose you have already resolved this issue? Can I close the issue?

**Comment by kobenguyent** [comment]
@evjlobanova yes please :)
