### ISSUE TITLE
Add a possibility to switch GA on/off

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/client-javascript#55]
Pros:
- good for understanding activity

Cons:
- Affects reporting? Machine where I execute tests doesn't have an access to network outside
- I immediately stops to trust this package

Solution:
Introduce analytics option on server side. Admin, who installed RP, is prompted to accept/decline telemetry. All agents will send http packets with `UserAgent` header, and then server will post analytic to centralized storage, which is public obviously.

**Comment by BorisOsipov** [comment]
I agree with @nvborisenko 

I use tools like marathon test runner which has build in analytics reporting usage, but it is disabled by default. It is end user choise enable\disable it.

**Comment by BorisOsipov** [comment]
@nvborisenko btw tools like allure report has the same feature. When you generate report it is send analytics data. see 
https://github.com/allure-framework/allure2/blob/master/Analytics.md
but it is documented at least.

**Comment by DzmitryHumianiuk** [comment]
Once we introduce it to all agents, we will make it documented.

Reason to have it: we need to understand scope of usage.

Posting it from individual servers to centralized storage required implementation of this kind of storage, unless it is the Google Analytics as well.

**Comment by nvborisenko** [comment]
I hate the idea to collect usage from agents. The most popular question is what kind of data this "tooling" sends outside when I propose RP as primary test reporting system. This question is critical for Great Britain.

I don't mind any centralized analytics storage, Google Analytics, whatever, but I am against that my data is leaking...

**Comment by DzmitryHumianiuk** [comment]
One can say that 'i hate that my statistics send from server to somewhere'.

The plan is to describe what kind of information agents will send.
It will be general info like:
- rp-agent name
- rp-agent version
- rp-client version

Once it described in open manner will it resolve the issue?

**Comment by BorisOsipov** [comment]
>The plan is to describe what kind of information agents will send.
👍

>will it resolve the issue?

IMO - not. Add option to disable\enable analytics - it can be enabled by default, but user should be able to completely disable it.

**Comment by nvborisenko** [comment]
One more important point: user **should be notified** in any way that package sends some info to 3rd-parties services. It's tricky with package manager, like nuget in .net world (even there are others package managers in .net). The problem is package cannot notify user, there is no UI.

**Comment by DzmitryHumianiuk** [comment]
This could be easily resolved with **Terms and Conditions** in package description.
At least a link to repository, were this should be described.

**Comment by DzmitryHumianiuk** [comment]
Well, we will do next:
- document in agents and clients that they send GA tick (kind of +1) at the moment of start
- add mechanism to disable it, but will keep it enabled by default

**Comment by AmsterGet** [comment]
This feature was released in [v5.0.1](https://github.com/reportportal/client-javascript/releases/tag/v5.0.1).
See the [startLaunch](https://github.com/reportportal/client-javascript#startlaunch) section in the README.
