### ISSUE TITLE
Getting error code 400 from Report Portal - [Field 'startTime' shouldn't be null.] "}

### ISSUE THREAD

**Issue by saravanan-autodev** [reportportal/client-javascript#65]
Getting the below error when trying to integrate Cucumber with Report Portal 
[16:45:00] I/launcher - Running 1 instances of WebDriver
[16:45:00] I/hosted - Using the selenium server at http://10.244.28.58:4444/wd/hub
.Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}    at Z:\Documents\report-portal-js-agent\node_modules\reportportal-client\lib\rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

Please have a look and help me on the next steps. Thanks.

**Comment by DiscoElevator** [comment]
@saravanan-autodev Hello. Which RP version do you use?

**Comment by DiscoElevator** [comment]
Also, current agent version from NPM doesn't work with RP v5. You can install agent from the master branch directly to use with RP v5.

**Comment by evjlobanova** [comment]
@saravanan-autodev please try to perform actions, which @DiscoElevator described.
If issue is still reproducing, please reopen it

**Comment by saravanan-autodev** [comment]
Hello @DiscoElevator / @evjlobanova - I haved installed the agent from master and tried to run the examples with the my report portal details but getting the below error
![image](https://user-images.githubusercontent.com/62570501/78817615-6afecb00-79a1-11ea-802b-93e633424b2a.png)

Report portal version which i use:
![image](https://user-images.githubusercontent.com/62570501/78817688-85d13f80-79a1-11ea-9094-b0c4e94a1798.png)

Kindly let me know if I am missing anything
