### ISSUE TITLE
Getting error code 400 from Report Portal - [Field 'startTime' shouldn't be null.] "}

### ISSUE THREAD

**Issue by saravanan-autodev** [reportportal/client-javascript#69]
Getting the below error when trying to integrate Cucumber with Report Portal
[16:45:00] I/launcher - Running 1 instances of WebDriver
[16:45:00] I/hosted - Using the selenium server at http://10.244.28.58:4444/wd/hub
.Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "} at Z:\Documents\report-portal-js-agent\node_modules\reportportal-client\lib\rest.js:27:23
at processTicksAndRejections (internal/process/task_queues.js:94:5)

Please have a look and help me on the next steps. Thanks.

I have raised the same issue in Issue #65. 
I have followed the same what was provided in the comments and getting the same error.
Hello @DiscoElevator / @evjlobanova - I haved installed the agent from master and tried to run the examples with the my report portal details but getting the below error.

Execution error
![image](https://user-images.githubusercontent.com/62570501/78818408-9f26bb80-79a2-11ea-88df-b3901be50c2a.png)

Report Portal
![image](https://user-images.githubusercontent.com/62570501/78818344-84ecdd80-79a2-11ea-88d7-63221101df28.png)

**Comment by DiscoElevator** [comment]
https://github.com/reportportal/agent-js-cucumber/issues/41#issuecomment-615217379

> Looks like it's because of broken backward compatibility in the reportportal-client.
As a workaround, you can install reportportal-client version 5.2.3.
Please let me know if it helped.

**Comment by AmsterGet** [comment]
Closed as a resolved according to [this](https://github.com/reportportal/agent-js-cucumber/issues/41#issuecomment-615217379) comment.
