### ISSUE TITLE
sendFile produces incorrect request

### ISSUE THREAD

**Issue by rst5nn** [reportportal/client-javascript#8]
Report Portal expect that json part of multi-form quest will be an array.

That is why, I think, need to fix client
from : `data: _self.buildMultiPartStream(saveLogRQ, file, boundary),`
to     :`data: _self.buildMultiPartStream([saveLogRQ], file, boundary),`

Please, correct me if I'am wrong.

**Comment by DzmitryHumianiuk** [comment]
@krasoffski Would you like to create PR?

**Comment by rst5nn** [comment]
Closed, because `saveLogRQ` should be an array. See following [pr](https://github.com/reportportal/client-javascript/pull/9).
