### ISSUE TITLE
import RP_STATUSES

### ISSUE THREAD

**Issue by yacovg** [reportportal/client-javascript#85]
How can I import RP_STATUSES from constants?

I've tried
import { RP_STATUSES } from '@reportportal/client-javascript';

**Comment by AmsterGet** [comment]
> How can I import RP_STATUSES from constants?
> 
> I've tried
> import { RP_STATUSES } from '@reportportal/client-javascript';

Hi @yacovg !
Have you tried the direct path to statuses?
Common JS:
```javascript
const { RP_STATUSES } = require('@reportportal/client-javascript/lib/constants/statuses');
```
ES6 modules, TypeScript:
```javascript
import { RP_STATUSES } from '@reportportal/client-javascript/lib/constants/statuses';
```

**Comment by AmsterGet** [comment]
Hope the answer above helps you!
I'll close this issue, feel free to reopen it.
