### ISSUE TITLE
Merge launches does not include more than 20 launches

### ISSUE THREAD

**Issue by wiibaker** [reportportal/client-javascript#86]
I started to use the new RP 5 versions of "client-javascript" and "agent-js-cypress" and noticed that if there are more than 20 launches to be merged only the first 20 are included in the merged launch. Remaining are left as is. The problem seems to be that the ReportPortal API returns by default only 20 launches, thus, cropping the rest out.

We are using the manual merging option in "agent-js-cypres", but not sure if that really matters.

This could be fixed at https://github.com/reportportal/client-javascript/blob/master/lib/report-portal-client.js#L280 by adding the  `page.size` parameter to the search parameters like this:

```
            const params = new URLSearchParams({
                'filter.in.uuid': launchUUIds,
                'page.size': launchUUIds.length,
            });
```

Not able to create the pull request myself as I already have forked the repo and cannot delete the fork currently. For us this is a blocker issue and not able to use the new versions before this is fixed.

**Comment by evjlobanova** [comment]
@AmsterGet @ElenaRomanchuk Could you please check this issue

**Comment by ElenaRomanchuk** [comment]
@wiibaker You can try to merge launches automatically by using https://github.com/reportportal/agent-js-cypress#automatically-merge-launches. It should works with any numbers of launches.
@evjlobanova This bug looks actual.

**Comment by wiibaker** [comment]
@ElenaRomanchuk at least at the moment we can't as we need to do some additional reporting calculations on the results :(

Btw... don't know if there is some hard limitation on the ```page.size``` which would just push the problem further, unless going through the results page by page.

**Comment by AmsterGet** [comment]
@Yumfriez could you please share the API page size limitation for launches?

**Comment by gustawx** [comment]
@wiibaker good point regarding max page.size, in my test run I have almost 2000 tests so I think this could be problematic. I think the best solution is to iterate through all pages and collect the results.
