### ISSUE TITLE
error when I try to use @reportportal/agent-js-mocha

### ISSUE THREAD

**Issue by SergeFix** [reportportal/client-javascript#96]
I have downloadedd the latets version of @reportportal/agent-js-mocha yesterday and have next result.
> node main.js

Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to launch run. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to create suite. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}       
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to create child item. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}  
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to create child item. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to create child item. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}  
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to finish child item. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to finish child item. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}  
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to finish child item. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}  
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to finish suite. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}       
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to finish run. Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at D:\Projects\Laika\ATM\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by AmsterGet** [comment]
Hi @SergeFix !
Which version of Report Portal are you using?

**Comment by SergeFix** [comment]
Hi
"@reportportal/client-javascript": "^5.0.0"

**Comment by AmsterGet** [comment]
I mean the RP core product :)
This is necessary because 5.* agents are only compatible with RP version 5.*.

**Comment by AmsterGet** [comment]
You can find the version numbers as in the screenshot below.

![image](https://user-images.githubusercontent.com/31861805/92904792-d0ad2280-f42b-11ea-9e7c-1334e7aa85c3.png)

**Comment by SergeFix** [comment]
![image](https://user-images.githubusercontent.com/48064792/92906908-862ca580-f42d-11ea-8264-5c45f826d62b.png)

**Comment by AmsterGet** [comment]
Got it.
As I mentioned above 5.* agents are only compatible with RP version 5.*.
So to use `@reportportal/agent-js-mocha` you need the RP version 5.* (you can try the demo instance from our landing page - https://reportportal.io/).
To use mocha with reporting to RP v4 you can use the deprecated https://www.npmjs.com/package/rp-mocha-reporter.

**Comment by SergeFix** [comment]
Thank you for fast answers and patience ))
